[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
fs_permissions = [
  { access = "read", path = "./script" }     # permite leer cualquier archivo dentro de /script
]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@uniswap/universal-router/=lib/universal-router/contracts/",
  "@uniswap/permit2/=lib/permit2/src/"
]

[rpc_endpoints]
mainnet       = "${ETH_RPC_URL}"                    
sepolia       = "${SEPOLIA_RPC_URL}"                 
mainnet_fork  = "${TENDERLY_MAINNET_FORK_RPC_URL}"   
tenderly_vnet = "${TENDERLY_VNET_RPC_URL}"          

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
